Add toggle for whitespace
ModOrganizer2/modorganizer-uibase pull request #138
Opened 2023-11-01 06:03 UTC by Silarn

2023-11-01 08:26 UTC, Holt59 requested changes

2023-11-01 08:26 UTC, Holt59 commented on src/textviewer.h
> +  void showWhitespace_changed(int state);
The other slots are full camel-case, could this be changed to `showWhitespaceChanged`?

2023-11-05 18:43 UTC, Silarn commented
Yeah, some of the older automated slots that Qt made were formatted this way and I sometimes want to keep using this naming convention out of habit, but I can rename it.

2023-11-05 18:52 UTC, Holt59 approved these changes

2023-11-05 18:55 UTC, merged